### ISSUE TITLE
[Discussion] Architecture Concepts and Libraries in Unit Tests

### ISSUE THREAD

**Issue by h0lydev** [freenowtech/Sensor#3]
I really liked the way you're working. I've been working with MVVM-RxSwift-Coordinators for the last projects and when I saw your architecture I could realize that is easier to scale than the way I've been working. 

I liked so much that I decided to start a new personal project using your way of working. But I have some doubts about the project:

- I could see a "Context" used in the Store but actually it's empty and doesn't affect the way the project is working. What could be this concept? 

- Do you use some third libraries to mock the json on unit tests, such as https://github.com/kylef/Mockingjay? 

Thank you in advance!

**Comment by mdellagi77** [comment]
Hey. Sorry for the late answer but it was the beginning of the new year and lot of people were just coming back this week. 

Two quickly answer your questions: 
1. Good catch. We are having a context in the view model. We have not finalized it but we are constantly improving and refining our architecture. Meaning we want to pass _use cases_ to the view model though this context. We are already using use cases, but we are not completely happy with the way we are using them right now. Therefore we decided to take them out in the last second. We have forgotten to remove the context reference. Sorry for the confusion. 

Please except an addition to the project soon sporting use cases and getting that context to work! 

2. In short. No we are not. But we will look into that. Thanks!

**Comment by h0lydev** [comment]
@mdellagi77 thank you so much for the feedback. I really appreciate the work. I understand that, mainly at the beginning, we have a lot to improve, but as I said, it's already a great path you've taken. 

Now just one more question, I'm trying to testing cases where I have side effects similar to your login sample. I realized that to async operations I cannot get the right value because the state it's not called. Only the state previous of the side effect. 

How have you been through this? Because with MVC I would use a RxBlocking to get async operations and test their result, but now I just want to test the state transition like in your example of Login(the sample you provided has the same problem, it doesn't hits the new state).

Thank you for you support guys!

**Comment by mdellagi77** [comment]
Hey h0lydev. 
I hope I am understanding you correctly.

If you look at `testCorrectLogin ` you see that we are calling 
```
let scheduler = TestScheduler(initialClock: 0, resolution: 1, simulateProcessingDelay: false)
SharingScheduler.mock(scheduler: scheduler)
``` 
That way we are making sure that a test scheduler is used. The event `loggedIn` which is coming in after a delay is being delivered only three ticks later instead of three actual seconds.
This will allow testing asynchronous events being fed back into the reducer! It works for us with here with the same project.

PS: Sorry for the long delay! We are actually more active here from now on and have dedicated ourselves to be more timely in our responses! Sorry again!

**Comment by mdellagi77** [comment]
Just checked out the repo as I reread your message. 
Two tests were failing, but not because the effects were not coming back into the reducer, 
but because the delay that is simulating network lag had been changed to 1 second instead of 3. Therefore the tests had to be adjusted to take this into account. 
Please look at the commit which fixes the tests!

Have a nice day

**Comment by mdellagi77** [comment]
https://github.com/mytaxi/LoginRxReduxDemo/commit/1e240720ec6701faac7f8c212e45118cea5dcc37#diff-dd86bbc31b97e937f57c27d1365e880e
